siteTitle="uTool"
siteDescription="µTool (/mu:tool/) creates data-driven digital products and services that give brands a competitive edge."
siteUrl= "http://utool.io"
siteVersion= "1.0.0"
copyrightMessage= "<a href='http://utool.io' target='_blank'>µTool</a>. All Rights reserved."
linkPrefix= ""
#gaCode= "UA-68653561-1"
